from .student import *
from .course import *
from .seating import *
from .exam import *
from .branch import *
from .room import *
from .allocation import *
from .seat_allocation import *
from .subject import *
from .department import *