"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { Separator } from "@/components/ui/separator"
import { Save, RotateCcw, Settings } from "lucide-react"

export function Configurations() {
  const [config, setConfig] = useState({
    defaultRows: 6,
    defaultColumns: 5,
    maxCapacity: 30,
    examGuidelines: `1. Students must arrive 15 minutes before the exam starts.
2. Mobile phones and electronic devices are strictly prohibited.
3. Only permitted materials (pen, pencil, ID card) are allowed.
4. Students must sign the attendance sheet.
5. No student shall leave the hall during the first 30 minutes.`,
    strictDeptInterleaving: true,
    allowSupplyStudents: true,
    autoGenerateDutyChart: false,
    sendEmailNotifications: true,
  })

  const handleSave = () => {
    // Save configuration logic
    console.log("Configuration saved:", config)
  }

  const handleReset = () => {
    setConfig({
      defaultRows: 6,
      defaultColumns: 5,
      maxCapacity: 30,
      examGuidelines: `1. Students must arrive 15 minutes before the exam starts.
2. Mobile phones and electronic devices are strictly prohibited.
3. Only permitted materials (pen, pencil, ID card) are allowed.
4. Students must sign the attendance sheet.
5. No student shall leave the hall during the first 30 minutes.`,
      strictDeptInterleaving: true,
      allowSupplyStudents: true,
      autoGenerateDutyChart: false,
      sendEmailNotifications: true,
    })
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">System Configuration</h1>
          <p className="text-muted-foreground">Configure default settings for the examination system</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleReset}>
            <RotateCcw className="w-4 h-4 mr-2" />
            Reset to Default
          </Button>
          <Button onClick={handleSave}>
            <Save className="w-4 h-4 mr-2" />
            Save Changes
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Room Matrix Settings */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Settings className="w-5 h-5" />
              Room Matrix Settings
            </CardTitle>
            <CardDescription>Configure default room dimensions and capacity</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="defaultRows">Default Rows</Label>
                <Input
                  id="defaultRows"
                  type="number"
                  value={config.defaultRows}
                  onChange={(e) =>
                    setConfig({ ...config, defaultRows: parseInt(e.target.value) || 0 })
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="defaultColumns">Default Columns</Label>
                <Input
                  id="defaultColumns"
                  type="number"
                  value={config.defaultColumns}
                  onChange={(e) =>
                    setConfig({ ...config, defaultColumns: parseInt(e.target.value) || 0 })
                  }
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="maxCapacity">Max Capacity per Room</Label>
              <Input
                id="maxCapacity"
                type="number"
                value={config.maxCapacity}
                onChange={(e) =>
                  setConfig({ ...config, maxCapacity: parseInt(e.target.value) || 0 })
                }
              />
            </div>
            <div className="bg-muted p-3 rounded-lg">
              <p className="text-sm text-muted-foreground">
                Default Matrix: <strong className="text-foreground">{config.defaultRows} × {config.defaultColumns}</strong> = {config.defaultRows * config.defaultColumns} seats
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Allocation Settings */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Allocation Settings</CardTitle>
            <CardDescription>Configure seating allocation behavior</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Strict Department Interleaving</Label>
                <p className="text-sm text-muted-foreground">
                  Ensure students from different departments sit alternately
                </p>
              </div>
              <Switch
                checked={config.strictDeptInterleaving}
                onCheckedChange={(checked) =>
                  setConfig({ ...config, strictDeptInterleaving: checked })
                }
              />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Allow Supply Students</Label>
                <p className="text-sm text-muted-foreground">
                  Include supplementary exam students in allocation
                </p>
              </div>
              <Switch
                checked={config.allowSupplyStudents}
                onCheckedChange={(checked) =>
                  setConfig({ ...config, allowSupplyStudents: checked })
                }
              />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Auto Generate Duty Chart</Label>
                <p className="text-sm text-muted-foreground">
                  Automatically assign invigilators after allocation
                </p>
              </div>
              <Switch
                checked={config.autoGenerateDutyChart}
                onCheckedChange={(checked) =>
                  setConfig({ ...config, autoGenerateDutyChart: checked })
                }
              />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Send Email Notifications</Label>
                <p className="text-sm text-muted-foreground">
                  Send automated emails to students and faculty
                </p>
              </div>
              <Switch
                checked={config.sendEmailNotifications}
                onCheckedChange={(checked) =>
                  setConfig({ ...config, sendEmailNotifications: checked })
                }
              />
            </div>
          </CardContent>
        </Card>

        {/* Exam Guidelines */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="text-lg">Exam Guidelines</CardTitle>
            <CardDescription>
              These guidelines will be printed on all examination documents
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              value={config.examGuidelines}
              onChange={(e) => setConfig({ ...config, examGuidelines: e.target.value })}
              className="min-h-[200px] font-mono text-sm"
            />
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
